// Auto-generated by quantize_model.py - do not edit.
// On-device parity constants for Rescue Pulse ESP32-S3 inference.
#ifndef MODEL_CONFIG_H
#define MODEL_CONFIG_H

// ---------- Audio front-end (must match extract_features.py) ----------
#define RP_SR       16000
#define RP_N_FFT    512
#define RP_HOP      256
#define RP_N_MFCC   13
#define RP_N_MELS   40
#define RP_FMIN     20
#define RP_FMAX     8000
#define RP_N_WIN    64
#define RP_PRE_EMPH 0.97f

// ---------- Per-coefficient standardization (train-set stats) ----------
static const float g_mfcc_mu[13]  = {-117.434525f, 4.487606f, -24.293510f, -3.709326f, -7.878681f, 0.391918f, 1.053018f, 0.541656f, -0.267191f, 1.199869f, -2.121182f, -0.288839f, -1.202343f};
static const float g_mfcc_std[13] = {58.905327f, 23.372980f, 16.025259f, 11.863704f, 10.669017f, 8.675331f, 8.650963f, 8.861771f, 7.564023f, 7.508868f, 7.631124f, 7.605318f, 6.853130f};

// ---------- TFLite int8 quantization parameters ----------
static const float g_in_scale  = 0.051951900124549866;
static const int   g_in_zp     = 13;
static const float g_out_scale = 0.00390625;
static const int   g_out_zp    = -128;

#endif // MODEL_CONFIG_H
