// Auto-generated by quantize_model.py - do not edit.
// On-device parity constants for Rescue Pulse ESP32-S3 inference.
#ifndef MODEL_CONFIG_H
#define MODEL_CONFIG_H

// ---------- Audio front-end (must match extract_features.py) ----------
#define RP_SR       16000
#define RP_N_FFT    512
#define RP_HOP      256
#define RP_N_MFCC   13
#define RP_N_MELS   40
#define RP_FMIN     20
#define RP_FMAX     8000
#define RP_N_WIN    64
#define RP_PRE_EMPH 0.97f

// ---------- Per-coefficient standardization (train-set stats) ----------
static const float g_mfcc_mu[13]  = {-100.882492f, 5.064211f, -20.384367f, -2.093422f, -5.939188f, 1.378855f, 1.060566f, 1.108511f, 0.412238f, 1.405284f, -1.298676f, 0.478767f, -0.759686f};
static const float g_mfcc_std[13] = {63.787781f, 20.363426f, 13.562347f, 9.212452f, 8.492233f, 6.858048f, 6.934321f, 6.731266f, 6.046873f, 5.777822f, 5.766019f, 5.729012f, 5.243539f};

// ---------- TFLite int8 quantization parameters ----------
static const float g_in_scale  = 0.05951277166604996;
static const int   g_in_zp     = 1;
static const float g_out_scale = 0.00390625;
static const int   g_out_zp    = -128;

#endif // MODEL_CONFIG_H
