// Auto-generated by quantize_model.py - do not edit.
// On-device parity constants for Rescue Pulse ESP32-S3 inference.
#ifndef MODEL_CONFIG_H
#define MODEL_CONFIG_H

// ---------- Audio front-end (must match extract_features.py) ----------
#define RP_SR       16000
#define RP_N_FFT    512
#define RP_HOP      256
#define RP_N_MFCC   13
#define RP_N_MELS   40
#define RP_FMIN     20
#define RP_FMAX     8000
#define RP_N_WIN    64
#define RP_PRE_EMPH 0.97f

// ---------- Per-coefficient standardization (train-set stats) ----------
static const float g_mfcc_mu[13]  = {-118.079803f, 4.486426f, -24.299124f, -3.709732f, -7.881674f, 0.390995f, 1.050675f, 0.540529f, -0.268264f, 1.198034f, -2.121210f, -0.290062f, -1.202998f};
static const float g_mfcc_std[13] = {63.284061f, 23.390852f, 16.044489f, 11.886513f, 10.672849f, 8.675402f, 8.650404f, 8.861875f, 7.565106f, 7.508941f, 7.631905f, 7.605822f, 6.853554f};

// ---------- TFLite int8 quantization parameters ----------
static const float g_in_scale  = 0.05669400840997696;
static const int   g_in_zp     = 15;
static const float g_out_scale = 0.00390625;
static const int   g_out_zp    = -128;

#endif // MODEL_CONFIG_H
